/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AiAssistantConversation {
  context_entity_id: string | null;
  context_entity_type: string | null;
  context_module: string | null;
  conversation_id: Generated<string>;
  is_active: Generated<boolean>;
  last_message_at: Timestamp | null;
  message_count: Generated<number>;
  started_at: Generated<Timestamp>;
  tenant_id: string;
  user_id: string;
}

export interface AiAssistantMessage {
  content: string;
  conversation_id: string;
  cost_usd: Numeric | null;
  created_at: Generated<Timestamp>;
  latency_ms: number | null;
  message_id: Generated<string>;
  model_used: string | null;
  rag_sources: Json | null;
  role: string;
  tokens_used: number | null;
}

export interface AiEvaluationDataset {
  created_at: Generated<Timestamp>;
  dataset_id: Generated<string>;
  dataset_name: string;
  difficulty_level: number | null;
  evaluation_type: string;
  expected_output: Json;
  input_data: Json;
  source: string | null;
  tags: string[] | null;
}

export interface AiGenerationLog {
  confidence_score: Numeric | null;
  cost_usd: Numeric | null;
  created_at: Generated<Timestamp>;
  edit_distance_pct: Numeric | null;
  generation_id: Generated<string>;
  generation_type: string;
  human_rating: number | null;
  input_context: Json | null;
  input_tokens: number | null;
  latency_ms: number | null;
  linked_entity_id: string | null;
  linked_entity_type: string | null;
  model_name: string;
  model_provider: string;
  output_content_hash: string | null;
  output_tokens: number | null;
  prompt_template: string | null;
  rag_chunks_retrieved: number | null;
  rag_retrieval_score: Numeric | null;
  tenant_id: string;
  was_accepted: boolean | null;
  was_edited: boolean | null;
}

export interface AiModelPerformance {
  accuracy_score: Numeric | null;
  avg_edit_distance: Numeric | null;
  created_at: Generated<Timestamp>;
  dataset_id: string | null;
  evaluation_date: Timestamp;
  evaluation_type: string;
  f1_score: Numeric | null;
  hallucination_rate: Numeric | null;
  human_approval_rate: Numeric | null;
  is_drift_detected: Generated<boolean>;
  model_name: string;
  notes: string | null;
  performance_id: Generated<string>;
  precision_score: Numeric | null;
  recall_score: Numeric | null;
  sample_size: number | null;
}

export interface CoreFacility {
  address_line1: string | null;
  address_line2: string | null;
  branch_id: string | null;
  branch_name: string | null;
  capacity_unit: string | null;
  city: string;
  city_code: string | null;
  climate_zone: string | null;
  commissioning_date: Timestamp | null;
  country_code: string;
  country_name: string;
  created_at: Generated<Timestamp>;
  decommissioning_date: Timestamp | null;
  facility_code: string;
  facility_id: Generated<string>;
  facility_name: string;
  facility_type: string;
  floor_area_sqm: Numeric | null;
  grid_region: string | null;
  is_active: Generated<boolean>;
  latitude: Numeric | null;
  lease_end_date: Timestamp | null;
  lease_start_date: Timestamp | null;
  longitude: Numeric | null;
  operating_days_year: number | null;
  operating_hours_day: Numeric | null;
  org_id: string;
  ownership_type: string | null;
  postal_code: string | null;
  production_capacity: Numeric | null;
  state_code: string | null;
  state_name: string | null;
  tenant_id: string;
  timezone: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CoreNotification {
  body: string | null;
  created_at: Generated<Timestamp>;
  is_read: Generated<boolean>;
  link_entity_id: string | null;
  link_entity_type: string | null;
  link_module: string | null;
  notification_id: Generated<string>;
  notification_type: string;
  read_at: Timestamp | null;
  tenant_id: string;
  title: string;
  user_id: string;
}

export interface CoreOrganization {
  address: string | null;
  annual_revenue_usd: Numeric | null;
  city: string | null;
  country_code: string;
  created_at: Generated<Timestamp>;
  employee_count: number | null;
  fiscal_year_start: Generated<number>;
  industry_code: string | null;
  industry_name: string | null;
  is_listed: Generated<boolean>;
  legal_name: string | null;
  market_cap_usd: Numeric | null;
  org_code: string;
  org_id: Generated<string>;
  org_name: string;
  org_type: string;
  parent_org_id: string | null;
  postal_code: string | null;
  registration_number: string | null;
  reporting_currency: Generated<string>;
  state_code: string | null;
  status: Generated<string>;
  stock_exchange: string | null;
  tax_id: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CorePermission {
  action: string;
  description: string | null;
  module: string;
  permission_code: string;
  permission_id: Generated<string>;
  resource: string;
}

export interface CoreRole {
  created_at: Generated<Timestamp>;
  description: string | null;
  is_system_role: Generated<boolean>;
  role_code: string;
  role_id: Generated<string>;
  role_name: string;
  tenant_id: string;
}

export interface CoreRolePermission {
  permission_id: string;
  role_id: string;
}

export interface CoreTenant {
  billing_currency: Generated<string>;
  contract_end: Timestamp | null;
  contract_start: Timestamp | null;
  created_at: Generated<Timestamp>;
  data_residency: Generated<string>;
  keycloak_realm_id: string | null;
  max_entities: Generated<number>;
  max_users: Generated<number>;
  status: Generated<string>;
  subscription_tier: Generated<string>;
  tenant_id: Generated<string>;
  tenant_name: string;
  tenant_slug: string;
  trial_expires_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface CoreUserAccount {
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  department: string | null;
  display_name: string | null;
  email: string;
  first_name: string | null;
  job_title: string | null;
  keycloak_user_id: string;
  last_login_at: Timestamp | null;
  last_name: string | null;
  login_count: Generated<number>;
  phone: string | null;
  preferred_language: Generated<string>;
  preferred_timezone: Generated<string>;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: Generated<string>;
}

export interface CoreUserRole {
  expires_at: Timestamp | null;
  facility_id: string | null;
  granted_at: Generated<Timestamp>;
  granted_by: string | null;
  org_id: string | null;
  role_id: string;
  user_id: string;
  user_role_id: Generated<string>;
}

export interface DqQualityCheckRun {
  critical_failures: Generated<number>;
  duration_ms: number | null;
  info_failures: Generated<number>;
  rules_failed: number;
  rules_passed: number;
  run_id: Generated<string>;
  run_timestamp: Generated<Timestamp>;
  status: string;
  tenant_id: string;
  total_rules_checked: number;
  trigger_type: string;
  warning_failures: Generated<number>;
}

export interface DqQualityException {
  actual_value: string | null;
  ai_explanation: string | null;
  assigned_at: Timestamp | null;
  assigned_to: string | null;
  created_at: Generated<Timestamp>;
  error_message: string;
  exception_id: Generated<string>;
  expected_value: string | null;
  resolution_notes: string | null;
  resolution_type: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  rule_id: string;
  run_id: string;
  severity: string;
  source_field: string | null;
  source_record_id: string | null;
  source_table: string;
  status: Generated<string>;
  suggested_action: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface DqQualityRule {
  created_at: Generated<Timestamp>;
  description: string | null;
  is_active: Generated<boolean>;
  rule_code: string;
  rule_id: Generated<string>;
  rule_logic: Json;
  rule_name: string;
  rule_type: string;
  severity: string;
  target_field: string | null;
  target_table: string;
}

export interface GovernApprovalRequest {
  approval_id: Generated<string>;
  approval_level: Generated<number>;
  approval_type: string;
  created_at: Generated<Timestamp>;
  current_approver_id: string | null;
  due_date: Timestamp | null;
  entity_description: string | null;
  entity_id: string;
  entity_type: string;
  is_overdue: Generated<boolean>;
  max_approval_level: Generated<number>;
  priority: Generated<string>;
  requested_at: Generated<Timestamp>;
  requested_by: string;
  resolution_comments: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  sla_hours: number | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface GovernApprovalStep {
  action_at: Timestamp | null;
  approval_id: string;
  approver_id: string;
  comments: string | null;
  status: Generated<string>;
  step_id: Generated<string>;
  step_level: number;
}

export interface GovernAuditEvent {
  action: string;
  after_state: Json | null;
  before_state: Json | null;
  change_summary: string | null;
  entity_id: string;
  entity_type: string;
  event_id: Generated<string>;
  event_timestamp: Generated<Timestamp>;
  event_type: string;
  metadata: Json | null;
  module: string;
  request_id: string | null;
  session_id: string | null;
  tenant_id: string;
  user_agent: string | null;
  user_email: string | null;
  user_id: string | null;
  user_ip: string | null;
}

export interface GovernComplianceDeadline {
  completed_at: Timestamp | null;
  completion_pct: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  deadline_id: Generated<string>;
  deadline_name: string;
  deadline_type: string;
  due_date: Timestamp;
  framework_id: string | null;
  last_reminder_sent: Timestamp | null;
  notes: string | null;
  org_id: string | null;
  reminder_days: Generated<number[]>;
  responsible_user_id: string | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface GovernMaterialityTopic {
  assessed_at: Timestamp | null;
  assessed_by: string | null;
  assessment_year: number;
  created_at: Generated<Timestamp>;
  description: string | null;
  esg_pillar: string;
  financial_materiality_score: Numeric | null;
  impact_materiality_score: Numeric | null;
  is_material: Generated<boolean>;
  linked_framework_metrics: string[] | null;
  materiality_threshold: Generated<Numeric>;
  notes: string | null;
  overall_materiality_score: Numeric | null;
  stakeholder_input: Json | null;
  tenant_id: string;
  topic_code: string;
  topic_id: Generated<string>;
  topic_name: string;
  updated_at: Generated<Timestamp>;
}

export interface MasterCarbonPrice {
  currency: string;
  jurisdiction: string;
  price_date: Timestamp;
  price_id: Generated<string>;
  price_per_tonne_local: Numeric;
  price_per_tonne_usd: Numeric;
  price_type: string;
  scheme_code: string;
  scheme_name: string;
  source: string | null;
}

export interface MasterCurrencyRate {
  exchange_rate: Numeric;
  from_currency: string;
  rate_date: Timestamp;
  rate_id: Generated<string>;
  source: string | null;
  to_currency: string;
}

export interface MasterEmissionFactor {
  activity_type: string | null;
  applicable_year: number;
  category: string;
  country_code: string | null;
  created_at: Generated<Timestamp>;
  effective_from: Timestamp;
  effective_to: Timestamp | null;
  factor_ch4: Generated<Numeric>;
  factor_co2: Generated<Numeric>;
  factor_code: string | null;
  factor_id: Generated<string>;
  factor_n2o: Generated<Numeric>;
  factor_total_co2e: Numeric;
  fuel_type: string | null;
  gas_type: string | null;
  gwp_ch4: Generated<Numeric>;
  gwp_co2: Generated<Numeric>;
  gwp_n2o: Generated<Numeric>;
  is_current: Generated<boolean>;
  notes: string | null;
  region: string | null;
  scope: string;
  source_id: string;
  subcategory: string | null;
  unit_of_measure: string;
  version: Generated<number>;
}

export interface MasterEmissionFactorSource {
  country_code: string | null;
  description: string | null;
  is_active: Generated<boolean>;
  publisher: string | null;
  source_code: string;
  source_id: Generated<string>;
  source_name: string;
  url: string | null;
}

export interface MasterFrameworkMetric {
  assurance_level: string | null;
  data_type: string;
  description: string | null;
  framework_id: string;
  is_mandatory: Generated<boolean>;
  metric_code: string;
  metric_id: Generated<string>;
  metric_name: string;
  platform_field_path: string | null;
  reporting_frequency: Generated<string>;
  section: string | null;
  subsection: string | null;
  unit_of_measure: string | null;
}

export interface MasterGhgGasType {
  chemical_formula: string | null;
  gas_category: string | null;
  gas_code: string;
  gas_id: Generated<string>;
  gas_name: string;
  gwp_ar5: Numeric | null;
  gwp_ar6: Numeric | null;
  is_kyoto_gas: Generated<boolean>;
}

export interface MasterIncentiveProgram {
  agency: string | null;
  applicable_activities: string[] | null;
  applicable_sectors: string[] | null;
  application_deadline: Timestamp | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  incentive_id: Generated<string>;
  incentive_type: string;
  is_active: Generated<boolean>;
  jurisdiction: string;
  max_amount_usd: Numeric | null;
  percentage_coverage: Numeric | null;
  program_code: string | null;
  program_end_date: Timestamp | null;
  program_name: string;
  program_start_date: Timestamp | null;
  url: string | null;
}

export interface MasterIndustryBenchmark {
  benchmark_id: Generated<string>;
  benchmark_value: Numeric;
  created_at: Generated<Timestamp>;
  geography: string | null;
  industry_code: string;
  industry_name: string;
  metric_name: string;
  metric_unit: string;
  percentile_25: Numeric | null;
  percentile_50: Numeric | null;
  percentile_75: Numeric | null;
  reference_year: number;
  source: string | null;
}

export interface MasterRegulatoryFramework {
  description: string | null;
  effective_date: Timestamp | null;
  first_reporting_year: number | null;
  framework_code: string;
  framework_id: Generated<string>;
  framework_name: string;
  framework_type: string;
  is_active: Generated<boolean>;
  issuing_body: string | null;
  jurisdiction: string;
  url: string | null;
}

export interface NetzeroPerformanceSummary {
  calculated_at: Generated<Timestamp>;
  org_id: string;
  overall_status: string | null;
  reporting_year: number;
  scope1_actual: Numeric | null;
  scope1_allowed: Numeric | null;
  scope1_gap: Numeric | null;
  scope2_actual: Numeric | null;
  scope2_allowed: Numeric | null;
  scope2_gap: Numeric | null;
  scope3_actual: Numeric | null;
  scope3_allowed: Numeric | null;
  scope3_gap: Numeric | null;
  summary_id: Generated<string>;
  tenant_id: string;
  total_actual: Numeric | null;
  total_allowed: Numeric | null;
  total_gap: Numeric | null;
}

export interface NetzeroTarget {
  approved_at: Timestamp | null;
  approved_by: string | null;
  base_emissions_co2e: Numeric;
  base_year: number;
  created_at: Generated<Timestamp>;
  emission_source_category: string | null;
  facility_id: string | null;
  ghg_scope_category: string;
  interim_targets: Json | null;
  is_sbti_validated: Generated<boolean>;
  org_id: string;
  projection_method: Generated<string>;
  reduction_pct: Numeric;
  sbti_method: string | null;
  sbti_validation_date: Timestamp | null;
  status: Generated<string>;
  target_code: string;
  target_emissions_co2e: Numeric;
  target_id: Generated<string>;
  target_name: string;
  target_type: string;
  target_year: number;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface NetzeroYearlyProjection {
  actual_emissions: Numeric | null;
  projection_id: Generated<string>;
  projection_year: number;
  status: string | null;
  target_id: string;
  variance: Numeric | null;
  yearly_allowed_emissions: Numeric;
}

export interface RecordDataSource {
  connection_config: Json | null;
  connector_type: string | null;
  created_at: Generated<Timestamp>;
  error_message: string | null;
  is_active: Generated<boolean>;
  last_sync_at: Timestamp | null;
  last_sync_records: number | null;
  last_sync_status: string | null;
  source_id: Generated<string>;
  source_name: string;
  source_type: string;
  sync_schedule: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface RecordDocumentUpload {
  confidence_score: Numeric | null;
  created_at: Generated<Timestamp>;
  document_id: Generated<string>;
  document_type: string;
  extraction_result: Json | null;
  facility_id: string | null;
  file_name: string;
  file_size_bytes: Int8 | null;
  file_type: string;
  linked_record_id: string | null;
  linked_record_type: string | null;
  org_id: string;
  processing_status: Generated<string>;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  storage_path: string;
  tenant_id: string;
  uploaded_by: string | null;
}

export interface RecordEmissionBatch {
  approved_at: Timestamp | null;
  approved_by: string | null;
  batch_id: Generated<string>;
  created_at: Generated<Timestamp>;
  data_source_id: string | null;
  facility_id: string;
  notes: string | null;
  org_id: string;
  period_id: string;
  record_count: Generated<number>;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  scope: string;
  submitted_at: Timestamp | null;
  submitted_by: string | null;
  tenant_id: string;
  total_cost: Numeric | null;
  total_emissions_co2e: Numeric | null;
  updated_at: Generated<Timestamp>;
  workflow_stage: Generated<string>;
}

export interface RecordEmissionConsolidated {
  calculated_at: Generated<Timestamp>;
  carbon_liability_usd: Numeric | null;
  carbon_price_used: Numeric | null;
  consolidation_id: Generated<string>;
  emission_intensity_employee: Numeric | null;
  emission_intensity_revenue: Numeric | null;
  energy_intensity_sqm: Numeric | null;
  facility_id: string | null;
  org_id: string;
  period_id: string;
  prior_period_total: Numeric | null;
  scope1_cost_usd: Generated<Numeric>;
  scope1_total: Generated<Numeric>;
  scope2_cost_usd: Generated<Numeric>;
  scope2_location: Generated<Numeric>;
  scope2_market: Generated<Numeric>;
  scope3_cost_usd: Numeric | null;
  scope3_total: Numeric | null;
  target_total: Numeric | null;
  tenant_id: string;
  total_all_scopes: Generated<Numeric>;
  variance_to_target: Numeric | null;
  yoy_change_pct: Numeric | null;
}

export interface RecordIotReading {
  anomaly_type: string | null;
  facility_id: string;
  is_anomaly: Generated<boolean>;
  raw_payload: Json | null;
  reading_id: Generated<string>;
  reading_timestamp: Timestamp;
  reading_unit: string;
  reading_value: Numeric;
  sensor_id: string;
  sensor_type: string;
  tenant_id: string;
}

export interface RecordReportingPeriod {
  created_at: Generated<Timestamp>;
  fiscal_year: string;
  locked_at: Timestamp | null;
  locked_by: string | null;
  org_id: string;
  period_end: Timestamp;
  period_id: Generated<string>;
  period_start: Timestamp;
  period_type: string;
  status: Generated<string>;
  tenant_id: string;
}

export interface RecordScope1Emission {
  activity_quantity: Numeric;
  activity_uom: string;
  batch_id: string;
  calculation_method: string | null;
  cost_currency: string | null;
  cost_usd: Numeric | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  data_source_type: string | null;
  ef_ch4: Generated<Numeric>;
  ef_co2: Generated<Numeric>;
  ef_n2o: Generated<Numeric>;
  emission_factor_id: string | null;
  emission_intensity: Numeric | null;
  emissions_ch4_kg: Generated<Numeric>;
  emissions_co2_kg: Generated<Numeric>;
  emissions_co2e_kg: Numeric;
  emissions_co2e_t: Numeric;
  emissions_n2o_kg: Generated<Numeric>;
  equipment_category: string;
  equipment_id: string | null;
  equipment_name: string | null;
  facility_id: string;
  fuel_type: string | null;
  gas_type: string | null;
  gwp_ch4: Generated<Numeric>;
  gwp_co2: Generated<Numeric>;
  gwp_n2o: Generated<Numeric>;
  notes: string | null;
  org_id: string;
  period_end: Timestamp;
  period_start: Timestamp;
  record_id: Generated<string>;
  source_document_id: string | null;
  tenant_id: string;
  total_cost: Numeric | null;
  uncertainty_pct: Numeric | null;
  unit_cost: Numeric | null;
  updated_at: Generated<Timestamp>;
}

export interface RecordScope2Emission {
  batch_id: string;
  cost_currency: string | null;
  cost_usd: Numeric | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  data_source_type: string | null;
  energy_quantity: Numeric;
  energy_supplier: string | null;
  energy_uom: string;
  facility_id: string;
  grid_region: string | null;
  is_renewable: Generated<boolean>;
  location_ef_ch4: Generated<Numeric>;
  location_ef_co2: Generated<Numeric>;
  location_ef_id: string | null;
  location_ef_n2o: Generated<Numeric>;
  location_emissions_co2e_kg: Numeric;
  location_emissions_co2e_t: Numeric;
  market_ef_id: string | null;
  market_emissions_co2e_kg: Generated<Numeric>;
  market_emissions_co2e_t: Generated<Numeric>;
  notes: string | null;
  org_id: string;
  period_end: Timestamp;
  period_start: Timestamp;
  rec_certificate_id: string | null;
  record_id: Generated<string>;
  renewable_pct: Generated<Numeric>;
  source_document_id: string | null;
  supplier_account_id: string | null;
  supplier_ef_ch4: Generated<Numeric>;
  supplier_ef_co2: Generated<Numeric>;
  supplier_ef_n2o: Generated<Numeric>;
  tariff_rate: Numeric | null;
  tariff_uom: string | null;
  tenant_id: string;
  total_cost: Numeric | null;
  updated_at: Generated<Timestamp>;
  utility_type: string;
}

export interface RecordScope3CategorySummary {
  calculated_at: Generated<Timestamp>;
  category_name: string;
  category_number: number;
  data_quality_avg: Numeric | null;
  org_id: string;
  period_id: string;
  primary_method: string | null;
  record_count: number;
  summary_id: Generated<string>;
  tenant_id: string;
  total_emissions_co2e_t: Numeric;
  total_spend_usd: Numeric | null;
}

export interface RecordScope3Emission {
  activity_description: string | null;
  activity_quantity: Numeric | null;
  activity_uom: string | null;
  batch_id: string;
  calculation_method: string;
  category_data: Json | null;
  category_name: string;
  category_number: number;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  data_quality_score: number | null;
  data_source_type: string | null;
  ef_unit: string | null;
  ef_value: Numeric | null;
  emission_factor_id: string | null;
  emissions_co2e_kg: Numeric;
  emissions_co2e_t: Numeric;
  facility_id: string | null;
  invoice_id: string | null;
  notes: string | null;
  org_id: string;
  period_end: Timestamp;
  period_start: Timestamp;
  record_id: Generated<string>;
  source_document_id: string | null;
  spend_amount: Numeric | null;
  spend_currency: string | null;
  spend_usd: Numeric | null;
  supplier_id: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ReduceInitiative {
  actual_carbon_reduction_co2e: Generated<Numeric>;
  actual_end_date: Timestamp | null;
  actual_saving_usd: Generated<Numeric>;
  actual_spend_usd: Generated<Numeric>;
  actual_start_date: Timestamp | null;
  approved_budget_usd: Numeric | null;
  budget_status: string | null;
  carbon_status: string | null;
  category: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  facility_id: string | null;
  health_indicator: string | null;
  initiative_code: string;
  initiative_id: Generated<string>;
  initiative_name: string;
  initiative_type: string | null;
  notes: string | null;
  opportunity_id: string | null;
  org_id: string;
  owner_name: string | null;
  owner_user_id: string | null;
  planned_end_date: Timestamp | null;
  planned_start_date: Timestamp | null;
  schedule_status: string | null;
  sponsor_user_id: string | null;
  target_annual_saving_usd: Numeric;
  target_carbon_reduction_co2e: Numeric;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  workflow_stage: Generated<string>;
}

export interface ReduceInitiativeClosure {
  budget_variance_usd: Numeric | null;
  carbon_variance_co2e: Numeric | null;
  closed_by: string | null;
  closure_date: Timestamp;
  closure_id: Generated<string>;
  closure_type: string;
  created_at: Generated<Timestamp>;
  initiative_id: string;
  lessons_learned: string | null;
  recommended_replications: string[] | null;
  replicability_score: number | null;
  success_rating: number | null;
  total_carbon_reduced: Numeric | null;
  total_saving_usd: Numeric | null;
  total_spend_usd: Numeric | null;
}

export interface ReduceInitiativeProgress {
  action_summary: string | null;
  blockers: string[] | null;
  carbon_reduced_cumulative: Numeric | null;
  carbon_reduced_period: Numeric | null;
  created_at: Generated<Timestamp>;
  initiative_id: string;
  milestones_completed: string[] | null;
  milestones_upcoming: string[] | null;
  progress_code: string | null;
  progress_id: Generated<string>;
  reported_by: string | null;
  reporting_date: Timestamp;
  saving_cumulative_usd: Numeric | null;
  saving_period_usd: Numeric | null;
  spend_cumulative_usd: Numeric | null;
  spend_period_usd: Numeric | null;
  title: string | null;
}

export interface ReduceMonitoringReading {
  actual_value: Numeric;
  alert_threshold_pct: Numeric | null;
  created_at: Generated<Timestamp>;
  data_source: string | null;
  initiative_id: string;
  is_alert: Generated<boolean>;
  metric_name: string;
  projected_value: Numeric;
  reading_date: Timestamp;
  reading_id: Generated<string>;
  sensor_id: string | null;
  variance: Numeric | null;
  variance_pct: Numeric | null;
}

export interface ReduceOpportunity {
  abatement_cost_per_tonne: Numeric | null;
  annual_saving_usd: Numeric;
  applicable_incentives: string[] | null;
  approved_at: Timestamp | null;
  approved_by: string | null;
  carbon_reduction_co2e: Numeric;
  carbon_reduction_pct: Numeric | null;
  category: string;
  complexity_score: number;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  dependencies: string[] | null;
  description: string | null;
  dismissed_reason: string | null;
  estimated_incentive_usd: Numeric | null;
  external_factors: string[] | null;
  facility_id: string | null;
  implementation_cost_usd: Generated<Numeric>;
  irr_pct: Numeric | null;
  notes: string | null;
  npv_usd: Numeric | null;
  opportunity_id: Generated<string>;
  opportunity_name: string;
  org_id: string;
  payback_months: number | null;
  phase: string;
  source_analysis_id: string | null;
  source_type: string;
  status: Generated<string>;
  subcategory: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ReduceShouldCostModel {
  benchmark_sources: string[] | null;
  calculation_logic: string | null;
  category: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  input_parameters: Json;
  is_active: Generated<boolean>;
  methodology: string | null;
  model_code: string;
  model_id: Generated<string>;
  model_name: string;
  subcategory: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ReduceTeardownAnalysis {
  actual_cost_usd: Numeric;
  actual_emissions_co2e: Numeric;
  analysis_id: Generated<string>;
  analysis_name: string | null;
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  facility_id: string;
  input_values: Json;
  model_id: string;
  notes: string | null;
  org_id: string;
  period_id: string;
  should_cost_usd: Numeric;
  should_emissions_co2e: Numeric;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  waste_cost_usd: Numeric;
  waste_decomposition: Json | null;
  waste_emissions_co2e: Numeric;
  waste_pct: Numeric | null;
}

export interface ReduceWastePool {
  actual_cost_usd: Numeric | null;
  analysis_id: string | null;
  calculated_at: Generated<Timestamp>;
  category: string;
  facility_id: string | null;
  org_id: string;
  period_id: string;
  pool_id: Generated<string>;
  should_cost_usd: Numeric | null;
  subcategory: string | null;
  tenant_id: string;
  waste_cost_usd: Numeric;
  waste_emissions_co2e: Numeric;
  waste_pct: Numeric | null;
}

export interface ReportConsistencyCheck {
  check_id: Generated<string>;
  check_name: string;
  check_type: string;
  created_at: Generated<Timestamp>;
  framework_a_id: string | null;
  framework_b_id: string | null;
  metric_description: string | null;
  period_id: string;
  resolution_notes: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  status: string;
  tenant_id: string;
  value_a: Numeric | null;
  value_b: Numeric | null;
  variance: Numeric | null;
}

export interface ReportExport {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  downloaded_at: Timestamp | null;
  downloaded_by: string | null;
  error_message: string | null;
  export_format: string;
  export_id: Generated<string>;
  export_purpose: string | null;
  file_name: string | null;
  file_size_bytes: Int8 | null;
  generated_at: Timestamp | null;
  generation_status: Generated<string>;
  report_id: string;
  storage_path: string | null;
  tenant_id: string;
}

export interface ReportFrameworkDataMapping {
  confidence_score: Numeric | null;
  created_at: Generated<Timestamp>;
  filter_conditions: Json | null;
  framework_metric_id: string;
  is_auto_mapped: Generated<boolean>;
  mapping_id: Generated<string>;
  platform_field: string;
  platform_table: string;
  tenant_id: string;
  transformation: string | null;
  updated_at: Generated<Timestamp>;
  validated_at: Timestamp | null;
  validated_by: string | null;
}

export interface ReportReport {
  ai_generation_completed_at: Timestamp | null;
  ai_generation_started_at: Timestamp | null;
  ai_model_used: string | null;
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  framework_id: string;
  generation_cost_usd: Numeric | null;
  human_edit_distance: Numeric | null;
  org_id: string;
  overall_completion_pct: Generated<Numeric>;
  overall_confidence: Numeric | null;
  period_id: string;
  published_at: Timestamp | null;
  report_id: Generated<string>;
  report_name: string;
  report_type: string;
  sections_auto_approved: Generated<number>;
  sections_human_edited: Generated<number>;
  status: Generated<string>;
  tenant_id: string;
  total_tokens_used: number | null;
  updated_at: Generated<Timestamp>;
}

export interface ReportReportSection {
  ai_generated_content: string | null;
  confidence_score: Numeric | null;
  content_type: string;
  created_at: Generated<Timestamp>;
  edit_distance_pct: Numeric | null;
  final_content: string | null;
  generation_status: Generated<string>;
  human_edited_content: string | null;
  metrics_included: Json | null;
  parent_section_id: string | null;
  report_id: string;
  review_comments: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  section_code: string;
  section_id: Generated<string>;
  section_name: string;
  section_order: number;
  source_data_refs: Json | null;
  updated_at: Generated<Timestamp>;
}

export interface SupplierInvoice {
  accounting_data: Json | null;
  approval_status: Generated<string>;
  approved_at: Timestamp | null;
  approved_by: string | null;
  calculation_method: string | null;
  carbon_adjusted_cost_usd: Numeric | null;
  carbon_cost_impact_pct: Numeric | null;
  carbon_liability_usd: Numeric | null;
  created_at: Generated<Timestamp>;
  document_id: string | null;
  facility_id: string | null;
  final_emissions_co2e: Numeric | null;
  invoice_currency: string;
  invoice_date: Timestamp;
  invoice_id: Generated<string>;
  invoice_number: string;
  invoice_value: Numeric;
  invoice_value_usd: Numeric | null;
  line_item_count: number | null;
  org_id: string;
  scope3_category: number | null;
  spend_based_emissions_co2e: Numeric | null;
  supplier_emissions_co2e: Numeric | null;
  supplier_id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SupplierInvoiceLineItem {
  description: string | null;
  emission_factor_id: string | null;
  emissions_co2e_kg: Numeric | null;
  invoice_id: string;
  line_currency: string | null;
  line_item_id: Generated<string>;
  line_number: number;
  line_total: Numeric;
  product_category: string | null;
  product_code: string | null;
  quantity: Numeric | null;
  scope3_category: number | null;
  unit_price: Numeric | null;
  uom: string | null;
}

export interface SupplierSupplier {
  annual_spend_usd: Numeric | null;
  cdp_score: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  country_code: string;
  created_at: Generated<Timestamp>;
  engagement_tier: string | null;
  esg_risk_score: number | null;
  has_cdp_disclosure: Generated<boolean>;
  has_sbti_target: Generated<boolean>;
  industry_code: string | null;
  industry_name: string | null;
  last_data_received: Timestamp | null;
  legal_registration: string | null;
  onboarding_status: Generated<string>;
  risk_category: string | null;
  sbti_commitment_type: string | null;
  spend_rank: number | null;
  status: Generated<string>;
  supplier_code: string;
  supplier_ef_ch4: Numeric | null;
  supplier_ef_co2: Numeric | null;
  supplier_ef_n2o: Numeric | null;
  supplier_ef_source: string | null;
  supplier_ef_year: number | null;
  supplier_id: Generated<string>;
  supplier_name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  website: string | null;
}

export interface SupplierSupplierOnboarding {
  created_at: Generated<Timestamp>;
  current_stage: Generated<string>;
  data_submitted_at: Timestamp | null;
  data_validated_at: Timestamp | null;
  invited_at: Timestamp | null;
  invited_by: string | null;
  notes: string | null;
  onboarding_id: Generated<string>;
  questionnaire_completed: Generated<boolean>;
  questionnaire_sent: Generated<boolean>;
  supplier_id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  validated_by: string | null;
}

export interface TaskPlan {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  due_date_rule: string | null;
  plan_id: Generated<string>;
  plan_name: string;
  priority: Generated<number>;
  schedule_cron: string | null;
  status: Generated<string>;
  tenant_id: string;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface TaskTask {
  assigned_to: string | null;
  completed_at: Timestamp | null;
  completed_by: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  due_date: Timestamp | null;
  linked_entity_id: string | null;
  linked_entity_type: string | null;
  linked_module: string | null;
  parent_task_id: string | null;
  plan_id: string;
  priority: Generated<string>;
  sequence_order: Generated<number>;
  status: Generated<string>;
  task_id: Generated<string>;
  task_name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "ai.assistant_conversation": AiAssistantConversation;
  "ai.assistant_message": AiAssistantMessage;
  "ai.evaluation_dataset": AiEvaluationDataset;
  "ai.generation_log": AiGenerationLog;
  "ai.model_performance": AiModelPerformance;
  "core.facility": CoreFacility;
  "core.notification": CoreNotification;
  "core.organization": CoreOrganization;
  "core.permission": CorePermission;
  "core.role": CoreRole;
  "core.role_permission": CoreRolePermission;
  "core.tenant": CoreTenant;
  "core.user_account": CoreUserAccount;
  "core.user_role": CoreUserRole;
  "dq.quality_check_run": DqQualityCheckRun;
  "dq.quality_exception": DqQualityException;
  "dq.quality_rule": DqQualityRule;
  "govern.approval_request": GovernApprovalRequest;
  "govern.approval_step": GovernApprovalStep;
  "govern.audit_event": GovernAuditEvent;
  "govern.compliance_deadline": GovernComplianceDeadline;
  "govern.materiality_topic": GovernMaterialityTopic;
  "master.carbon_price": MasterCarbonPrice;
  "master.currency_rate": MasterCurrencyRate;
  "master.emission_factor": MasterEmissionFactor;
  "master.emission_factor_source": MasterEmissionFactorSource;
  "master.framework_metric": MasterFrameworkMetric;
  "master.ghg_gas_type": MasterGhgGasType;
  "master.incentive_program": MasterIncentiveProgram;
  "master.industry_benchmark": MasterIndustryBenchmark;
  "master.regulatory_framework": MasterRegulatoryFramework;
  "netzero.performance_summary": NetzeroPerformanceSummary;
  "netzero.target": NetzeroTarget;
  "netzero.yearly_projection": NetzeroYearlyProjection;
  "record.data_source": RecordDataSource;
  "record.document_upload": RecordDocumentUpload;
  "record.emission_batch": RecordEmissionBatch;
  "record.emission_consolidated": RecordEmissionConsolidated;
  "record.iot_reading": RecordIotReading;
  "record.reporting_period": RecordReportingPeriod;
  "record.scope1_emission": RecordScope1Emission;
  "record.scope2_emission": RecordScope2Emission;
  "record.scope3_category_summary": RecordScope3CategorySummary;
  "record.scope3_emission": RecordScope3Emission;
  "reduce.initiative": ReduceInitiative;
  "reduce.initiative_closure": ReduceInitiativeClosure;
  "reduce.initiative_progress": ReduceInitiativeProgress;
  "reduce.monitoring_reading": ReduceMonitoringReading;
  "reduce.opportunity": ReduceOpportunity;
  "reduce.should_cost_model": ReduceShouldCostModel;
  "reduce.teardown_analysis": ReduceTeardownAnalysis;
  "reduce.waste_pool": ReduceWastePool;
  "report.consistency_check": ReportConsistencyCheck;
  "report.export": ReportExport;
  "report.framework_data_mapping": ReportFrameworkDataMapping;
  "report.report": ReportReport;
  "report.report_section": ReportReportSection;
  "supplier.invoice": SupplierInvoice;
  "supplier.invoice_line_item": SupplierInvoiceLineItem;
  "supplier.supplier": SupplierSupplier;
  "supplier.supplier_onboarding": SupplierSupplierOnboarding;
  "task.plan": TaskPlan;
  "task.task": TaskTask;
}
