-- Master load script: run all synthetic data files in dependency order
-- Generated for Brentford FC test data

\i core_tenant.sql
\i core_organization.sql
\i core_facility.sql
\i core_user_account.sql
\i core_role.sql
\i core_permission.sql
\i core_role_permission.sql
\i core_user_role.sql
\i core_notification.sql
\i master_emission_factor_source.sql
\i master_emission_factor.sql
\i master_currency_rate.sql
\i master_carbon_price.sql
\i master_industry_benchmark.sql
\i master_regulatory_framework.sql
\i master_framework_metric.sql
\i master_ghg_gas_type.sql
\i master_incentive_program.sql
\i record_data_source.sql
\i record_reporting_period.sql
\i record_emission_batch.sql
\i record_scope1_emission.sql
\i record_scope2_emission.sql
\i record_scope3_emission.sql
\i record_scope3_category_summary.sql
\i record_emission_consolidated.sql
\i record_document_upload.sql
\i record_iot_reading.sql
\i supplier_supplier.sql
\i supplier_invoice.sql
\i supplier_supplier_onboarding.sql
\i reduce_should_cost_model.sql
\i reduce_teardown_analysis.sql
\i reduce_waste_pool.sql
\i reduce_opportunity.sql
\i reduce_initiative.sql
\i reduce_initiative_progress.sql
\i reduce_monitoring_reading.sql
\i report_report.sql
\i report_report_section.sql
\i report_framework_data_mapping.sql
\i report_consistency_check.sql
\i report_export.sql
\i govern_approval_request.sql
\i govern_approval_step.sql
\i govern_audit_event.sql
\i govern_materiality_topic.sql
\i govern_compliance_deadline.sql
\i ai_generation_log.sql
\i ai_evaluation_dataset.sql
\i ai_model_performance.sql
\i ai_assistant_conversation.sql
\i ai_assistant_message.sql
\i dq_quality_rule.sql
\i dq_quality_check_run.sql
\i dq_quality_exception.sql
\i netzero_target.sql
\i netzero_yearly_projection.sql
\i netzero_performance_summary.sql
\i task_plan.sql
\i task_task.sql
